[package]
name = "valid"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_setters.workspace = true


[dev-dependencies]
pretty_assertions.workspace = true
serde.workspace = true
serde_json.workspace = true
stripmargin = "0.1.1"
serde_path_to_error = "0.1.16"
